ini
[global]
   workgroup = WORKGROUP
   security = user
   map to guest = Never
   usershare allow guests = no

   log file = /var/log/samba/log.%m
   max log size = 50

   # Аудит всех операций с файлами
   vfs objects = full_audit
   full_audit:prefix = %u|%I|%S
   full_audit:success = connect disconnect open opendir read write rename unlink mkdir rmdir
   full_audit:failure = none
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

# Каталоги с разграничением доступа

[strategy]
   path = /share/strategy
   browseable = yes
   read only = no
   guest ok = no
   valid users = @boss

[reports]
   path = /share/reports
   browseable = yes
   read only = no
   guest ok = no
   valid users = @boss @managers @analysts

[clients]
   path = /share/clients
   browseable = yes
   read only = no
   guest ok = no
   valid users = @boss @managers

[it]
   path = /share/it
   browseable = yes
   read only = no
   guest ok = no
   valid users = @admins
